language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - 3.7
  - 3.8

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  # Useful for debugging any issues with conda
  - conda info -a

  # Create environment and install dependences dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - conda install -q --yes compilers matplotlib pytest pytest-cov coveralls pip openmdao=3.4.0 jsonschema ruamel_yaml pyyaml make xlrd openpyxl cython pandas numpydoc six setuptools git numpy scipy geopy
  - pip install simpy marmot-agents

  # Install WISDEM
  #- python setup.py install
  - pip install -e .;

  
script:
  #- python test/test_all.py
  - pytest --cov-config=.coverageac --cov=wisdem

after_success:
  - coveralls
