channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
# NOTE: uncomment the OS-dependent lines below as needed
  # - m2w64-toolchain  # [win]
  # - libpython  # [win]
  # - gfortran  # [osx]  # only if not installed via homebrew or macports
  - petsc4py  # [unix]
  - mpi4py  # [unix] # only needed if local system has mpi built and is used
  - coveralls
  - cython
  - jsonmerge
  - jsonschema
  - matplotlib
  - moorpy>=1.2
  - ninja
  - nlopt
  - numpy
  - openmdao
  - openpyxl
  - pandas
  - pydoe3
  - pyoptsparse
  - pyyaml
  - scipy
  - sortedcontainers
  - statsmodels>=0.14.5
  - pip
  - pip:
    - orbit-nrel>=1.2.1
    - dearpygui
    - windIO
