channels:
  - conda-forge
  - defaults

dependencies:
  - coveralls
  - cython
  - jsonschema
  - make
  - matplotlib
  - meson
  - moorpy
  - ninja
  - nlopt=2.8.0
  - numpy
  - numpydoc
  - openmdao
  - openpyxl
  - pandas
  - pip
  - pydoe3
  - pyoptsparse
  - pytest
  - pytest-cov
  - python-benedict<0.33.2
  - pyyaml
  - ruamel.yaml
  - scipy
  - setuptools
  - simpy
  - sortedcontainers
  - statsmodels
  - swig
  - pip:
    - orbit-nrel>=1.2
    - dearpygui
# Needs to be done outside of environment file:
#  - m2w64-toolchain # [win]
#  - libpython # [win]
#  - compilers # [not win]
#  - petsc4py # [not win]
#  - mpi4py (only needed if local system has mpi built and is used)
