channels:
  - conda-forge
  - defaults

dependencies:
  - cftime
  - coveralls
  - cython
  - jsonmerge
  - jsonschema
  - make
  - matplotlib
  - meson
  - moorpy>=1.2
  - netcdf4
  - ninja
  - nlopt
  - numpy
  - numpydoc
  - openmdao
  - openpyxl
  - pandas
  - pip
  - pydoe3
  - pyoptsparse
  - pytest
  - pytest-cov
  - python-benedict
  - pyyaml
  - ruamel.yaml
  - scipy
  - setuptools
  - simpy
  - sortedcontainers
  - statsmodels>=0.14.5
  - swig
  - xarray
  - pip:
    - orbit-nrel>=1.2.1
    - dearpygui
    - windIO
# Needs to be done outside of environment file:
#  - m2w64-toolchain # [win]
#  - libpython # [win]
#  - compilers # [not win]
#  - petsc4py # [not win]
#  - mpi4py (only needed if local system has mpi built and is used)
