channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
# NOTE: uncomment the OS-dependent lines below as needed
  # - m2w64-toolchain  # [win]
  # - libpython  # [win]
  # - gfortran  # [osx]  # only if not installed via homebrew or macports
  # - petsc4py  # [unix]
  # - mpi4py  # [unix] # only needed if local system has mpi built and is used
  - cftime
  - coveralls
  - cython
  - jsonmerge
  - jsonschema
  - make
  - matplotlib
  - meson
  - moorpy>=1.2
  - netcdf4
  - ninja
  - nlopt
  - numpy
  - numpydoc
  - openmdao
  - openpyxl
  - pandas
  - pip
  - pydoe3
  - pyoptsparse
  - pytest
  - pytest-cov
  - pyyaml
  - scipy
  - setuptools
  - sortedcontainers
  - statsmodels>=0.14.5
  - swig
  - xarray
  - pip:
    - orbit-nrel>=1.2.1
    - dearpygui
    - windIO
    - "-e ."
