name: test

channels:
  - conda-forge
  - defaults

dependencies:
  - coveralls
  - cython
  - git
  - jsonschema
  - make
  - matplotlib
  - mpi4py
  - nlopt
  - numpy
  - openmdao>=3.4, <3.17
  - openpyxl
  - pandas
  - pip
  - pyside2
  - pytest
  - pytest-cov
  - python
  - python-benedict
  - pyyaml
  - ruamel_yaml
  - scipy
  - setuptools
  - simpy
  - sortedcontainers
  - statsmodels
  - swig
  - pip:
    - marmot-agents
# Needs to be done outside of environment file:
#  - m2w64-toolchain # [win]
#  - libpython # [win]
#  - compilers # [not win]
#  - petsc4py # [not win]
#  - pyoptsparse # [not win]
