channels:
  - conda-forge
  - defaults

dependencies:
  - coveralls
  - cython
  - git
  - jsonschema
  - make
  - matplotlib
  - meson
  - mpi4py
  - ninja
  - nlopt
  - numpy
  - numpydoc
  - openmdao>=3.18
  - openpyxl==3.1.0
  - pandas
  - pip
  - pydoe2
  - pyoptsparse
  - pytest
  - pytest-cov
  - python
  - python-benedict
  - pyyaml
  - ruamel_yaml
  - scipy
  - setuptools
  - simpy
  - sortedcontainers
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx_rtd_theme
  - statsmodels
  - swig
  - pip:
    - marmot-agents
    - dearpygui
# Needs to be done outside of environment file:
#  - m2w64-toolchain # [win]
#  - libpython # [win]
#  - compilers # [not win]
#  - petsc4py # [not win]
